package neu.edu.entity;
// Generated Apr 4, 2017 9:59:00 PM by Hibernate Tools 5.2.1.Final

/**
 * UserEducation generated by hbm2java
 */
public class UserEducation implements java.io.Serializable {

	private Integer eduId;
	private Integer userId;
	private String universityName;
	private String courseName;
	private String gpa;
	private String year;

	public UserEducation() {
	}

	public UserEducation(Integer userId, String universityName, String courseName, String gpa, String year) {
		this.userId = userId;
		this.universityName = universityName;
		this.courseName = courseName;
		this.gpa = gpa;
		this.year = year;
	}

	public Integer getEduId() {
		return this.eduId;
	}

	public void setEduId(Integer eduId) {
		this.eduId = eduId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUniversityName() {
		return this.universityName;
	}

	public void setUniversityName(String universityName) {
		this.universityName = universityName;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getGpa() {
		return this.gpa;
	}

	public void setGpa(String gpa) {
		this.gpa = gpa;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
