package neu.edu.entity;
// Generated Apr 4, 2017 9:59:00 PM by Hibernate Tools 5.2.1.Final

/**
 * UserAddress generated by hbm2java
 */
public class UserAddress implements java.io.Serializable {

	private Integer addressId;
	private String address;
	private String city;
	private String zip;
	private String state;
	private Integer userId;

	public UserAddress() {
	}

	public UserAddress(String address, String city, String zip, String state, Integer userId) {
		this.address = address;
		this.city = city;
		this.zip = zip;
		this.state = state;
		this.userId = userId;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
