package neu.edu.entity;
// Generated Apr 4, 2017 9:59:00 PM by Hibernate Tools 5.2.1.Final

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer userInfoId;
	private String firstName;
	private String lastName;
	private String dateOfBirth;
	private String email;
	private String careerSummary;
	private String linesAboutYourself;
	private Integer userId;

	public UserInfo() {
	}

	public UserInfo(String firstName, String lastName, String dateOfBirth, String email, String careerSummary,
			String linesAboutYourself, Integer userId) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
		this.careerSummary = careerSummary;
		this.linesAboutYourself = linesAboutYourself;
		this.userId = userId;
	}

	public Integer getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(Integer userInfoId) {
		this.userInfoId = userInfoId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCareerSummary() {
		return this.careerSummary;
	}

	public void setCareerSummary(String careerSummary) {
		this.careerSummary = careerSummary;
	}

	public String getLinesAboutYourself() {
		return this.linesAboutYourself;
	}

	public void setLinesAboutYourself(String linesAboutYourself) {
		this.linesAboutYourself = linesAboutYourself;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
