package neu.edu.entity;
// Generated Apr 4, 2017 9:59:00 PM by Hibernate Tools 5.2.1.Final

/**
 * UserProject generated by hbm2java
 */
public class UserProject implements java.io.Serializable {

	private Integer projectId;
	private Integer userId;
	private String projectName;
	private String projectDesc;

	public UserProject() {
	}

	public UserProject(Integer userId, String projectName, String projectDesc) {
		this.userId = userId;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

}
